# Generated by Django 5.1.2 on 2024-10-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_cliente_inicio_mapa_parqueadero_usuario_vehiculo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parqueadero',
            name='capacidad',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parqueadero',
            name='direccion',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parqueadero',
            name='nombre',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
