# Generated by Django 5.1.2 on 2024-10-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_usuario_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(default='Sin marca', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo_vehiculo',
            field=models.CharField(max_length=50),
        ),
    ]
