# Generated by Django 5.1.2 on 2024-10-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_vehiculo_marca_alter_vehiculo_placa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(default='Sin marca', max_length=50),
        ),
    ]
